#!/bin/sh
## Default PCI device passthrough
## Generated by process-lspci.sh

## IMPORT vfio management module
. /home/user/multiverse-os/scripts/sh-framework/modules/multiverse/vfio-management.sh

passthrough audio 1002:aaa0 0000:65:00.1
passthrough audio 1002:aaf8 0000:19:00.1
passthrough audio 8086:a2f0 0000:00:1f.3
passthrough display 1002:6798 0000:65:00.0
passthrough display 1002:6863 0000:19:00.0
passthrough input 1b21:2142 0000:03:00.0
passthrough input 1b21:2142 0000:06:00.0
passthrough input 1b21:2142 0000:07:00.0
passthrough input 8086:a2a3 0000:00:1f.4
passthrough input 8086:a2af 0000:00:14.0
passthrough network 168c:003e 0000:05:00.0
passthrough network 1ae9:0310 0000:02:00.0
passthrough network 8086:1539 0000:04:00.0
passthrough network 8086:15b8 0000:00:1f.6
